export {HomePage} from "./home/HomePage"
export {Contact} from "./contact/ContactPage"
export {Error} from "./error/Error"
import {ProductDetails} from "./productDetails/ProductDetails"
export {Register} from "./register/RegisterPage"
export { Login } from "./login/LoginPage"
export { AboutUs } from "./about/AboutPage"
export { UserDashboard } from "./users/UserDashboard"
export { AdminDashboard } from "./admin/AdminDashboard"
export { UserProfile } from "./users/UserProfile"
export { UserOrders } from "./users/UserOrders"
export { CartPage } from "./cart/CartPage"
